vim.api.nvim_create_user_command('W', 'write', {})
vim.api.nvim_create_user_command('Wq', 'wq', {})
vim.api.nvim_create_user_command('Q', 'quit', {})
vim.api.nvim_create_user_command('Qa', 'qall', {})
vim.api.nvim_create_user_command('Wqa', 'wqall', {})
vim.api.nvim_create_user_command('ClearBG', function()
    vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
    vim.api.nvim_set_hl(0, "NormalNC", { bg = "none" })
end, {})
vim.api.nvim_create_user_command('LG', ':term lazygit<cr>', {})
